### ISSUE TITLE
Ability to define dependencies to/from advanced services

### ISSUE THREAD

**Issue by sblandford** [nconf/nconf#21]
It is currently only possible to define dependencies between Services in the GUI. It would be useful to be able to declare dependencies between,

1) Advanced Services and Advanced Services
2) Services and Advances Services

My current set up consists of hosts mainly defined by Advanced Services with only one or two Services per host. This means my options for declaring inter-service dependencies are very limited.

**Comment by gargiulo** [comment]
I agree, this would be a very useful feature, especially between AS and AS. 
The ordinary services are sort of a legacy feature and should be replaced by advanced-services sometime. That will require implementing some of the missing functionality, as you have stated.
