### ISSUE TITLE
Will there be  a new release?

### ISSUE THREAD

**Issue by dwerder** [nconf/nconf#24]
Hi guys,

at first i want to say that I really like nconf. Good Work.

But the last Release 1.3 is more then 2 years ago. Will there be a new one or is something like that planed?

Regards

**Comment by gargiulo** [comment]
Hi. Thanks for your message.
Yes, there will be a small bugfix release soon. We are currently doing some changes to our development workflows so that we can release more frequently.

Regards,
Angelo
